### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yuki2216** [yuki2216/furima-33468#18]
自身のフリマアプリのURL
https://furima-33468.herokuapp.com
Basic認証のIDとパスワード
admin　　　2222
出品者用のメールアドレスとパスワード
1@1                    Aa000000
購入者用のメールアドレスとパスワード
2@2                   Aa000000
購入用カードの番号・期限・セキュリティコード
4242424242424242         2/23    123

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・編集ボタンを押すと添付画像にあるエラー画面に遷移してしまいます。こちらエラー画面が出ないように修正をお願い致します。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

<img width="576" alt="スクリーンショット 2021-02-08 9 29 45" src="https://user-images.githubusercontent.com/57244739/107164012-378d3280-69f0-11eb-90b9-0c54a265a2fe.png">

**Comment by vesper1102609** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**[修正依頼箇所]**

**●出品者であるにも関わらず、購入urlを入力すると購入画面に遷移できていしまいます。**
ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると、トップページに遷移するように修正しましょう。

出品した商品に直接購入URLを入力。
![image](https://user-images.githubusercontent.com/49742444/107181557-6fab6a00-6a1e-11eb-8661-e46c140f0174.png)
購入画面に遷移できてしまう。
![image](https://user-images.githubusercontent.com/49742444/107181568-789c3b80-6a1e-11eb-8c28-55bd2dbc49fd.png)

**●ログイン状態のユーザーであればsoldout商品であってもurlを直接入力すれば購入画面に遷移できてしまいます。**
ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品購入ページへ遷移しようとすると、トップページに遷移するよう修正しましょう。

購入済みの商品にURLを直接入力。
![image](https://user-images.githubusercontent.com/49742444/107181739-d29d0100-6a1e-11eb-9b87-eb2d3deab220.png)

購入画面に遷移できる。
![image](https://user-images.githubusercontent.com/49742444/107181747-d6c91e80-6a1e-11eb-8d51-fa0f4a18fdb7.png)

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
